### PR TITLE
Refactor Lexical and Finalize Documents

### PR DESCRIPTION
**Pull request by edilsalvador**
Lexical Analyzer:
- [x] Reserved Words
- [x] Reserved Symbols
- [x] String Literals
- [x] Character Literals
- [x] Integer Literals
- [x] Double Literals
- [x] Identifiers

Documents:
- [x] Rules
- [x] Transitional Diagram
- [x] Regular Definition
- [x] Regular Expression
- [x] Context Free Grammar

### CODE REVIEW

**Comment by clinomania** [comment]
Transitional Diagram Edited (refer to issue #14 ) " " and ' ' added.

**Comment by clinomania** [comment]
Updated Lexicom and Regular Expressions document (refer to #22)

**Comment by edilsalvador** [comment]
I'm just waiting for your documents.
Magmemerge na us! Dalian niyo. HAHAHA.
@shinzangetsu @clinomania @Winlynne3

**Comment by clinomania** [comment]
Updated Transitional Diagram: Added comma, editted the flow of literal and identifier (refer to issue #32 #30 and #29)

**Comment by clinomania** [comment]
Pacheck TD @edilsalvador Thanks! :smiley:

**Pull request merged**
