### PR TITLE
Conditional and Looping Statements CFG

### PR DESCRIPTION
**Pull request by clinomania**

### CODE REVIEW

**Comment by edilsalvador** [comment]
# Editted non-terminal statements and cond_loop.

```
Editted:
<statements> on Line 112
<cond_loop> on Line 152
<condstate> on Line 155
<if2> and <if3> on Lines 156 and 158

Added:
<functions> on Line 114
```

**Comment by clinomania** [comment]
# Added For Loop and Or Keyword:

```
Added:
Non-Terminal<loopstate> for For Loop on Lines 190 to 198
Or Keyword

Edited:
Otherwise If to Or on Line 157
```

**Comment by edilsalvador** [comment]
Please refer to issue #15 for simulation and checking.

**Comment by edilsalvador** [comment]
# CFG - Fixed Issues and Candidate for Merging

```
- Fixed all ambiguities
- Collapse Non-Terminals on <global>, <functions>, <objvar> and <io_statements>
- Fixed certain issues regarding issue #11 Program 1
- Candidate for merging
```

**Comment by edilsalvador** [comment]
# CFG - Reconfigure Last Commit for Merging

**Change the following:**
`- Removed <Ops> on <Conditions>
`
**Changes:**

```
1. <conditions>    ->    <ids><b>
2. <conditions>    ->    <logop2><conds>
3. <conds>    ->    (<conds_choice>)<b>
4. <conds>    ->    <input_id>
5. <conds>    ->    Boollit
6. <conds>    ->    <task_id>
7. <conds_choice>    ->    <ids>
8. <conds_choice>    ->    <task_id><Ops>
```

**Pull request merged**
